stages:
  - verify

verify:
  stage: verify
  image: node:23
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm/
  before_script:
    - npm ci
  script:
    - npm run lint
    - npm run typecheck
    - npm run test
    - npm run rewrite:check:strict
